{application,xml_test,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{xml_test_app,[]}},
              {env,[]},
              {modules,[xml_test_app,xml_test_client,xml_test_server,
                        xml_test_sup]}]}.
